export class SqlsParser {
    static aliases = {
        '-ddb-': 'DROP DATABASE IF EXISTS',
        '-cdb-': 'CREATE DATABASE',
        '-dtb-': 'DROP TABLE IF EXISTS',
        '-ctb-': 'CREATE TABLE',
        '-atb-': 'ALTER TABLE',
        '-acl': 'ADD COLUMN',
        '-mcl': 'MODIFY COLUMN',
        '-bf-': 'BEFORE',
        '-af-': 'AFTER',
        '-umb4-': 'utf8mb4',
        '-umb4gci-': 'utf8mb4_general_ci',
        '-dbumb4gci-': 'CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci',
        '-cs-': 'CHARACTER SET',
        '-cl-': 'COLLATE',
        '-csumb4-': 'CHARACTER SET utf8mb4',
        '-clumb4gci-': 'COLLATE utf8mb4_general_ci',
        '-u-': 'USE',
        '-i-': 'INT',
        '-iu-': 'INT UNSIGNED',
        '-iunn-': 'INT UNSIGNED NOT NULL',
        '-iudf-': 'INT UNSIGNED DEFAULT',
        '-iudf0-': 'INT UNSIGNED DEFAULT 0',
        '-iudf1-': 'INT UNSIGNED DEFAULT 1',
        '-iupk-': 'INT UNSIGNED PRIMARY KEY',
        '-iuaipk-': 'INT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
        '-idaipk-': 'id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
        '-idiuaipk-': 'id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY',
        '-d-': 'DECIMAL',
        '-dmoney-': 'DECIMAL(11, 2)',
        '-dbigmoney-': 'DECIMAL(21, 2)',
        '-dsci-': 'DECIMAL(12, 3)',
        '-dbigsci-': 'DECIMAL(22, 3)',
        '-dt-': 'DATE',
        '-dtt-': 'DATETIME',
        '-ts-': 'TIMESTAMP',
        '-c-': 'CHAR',
        '-vc-': 'VARCHAR',
        '-vc8-': 'VARCHAR(8)',
        '-vc16-': 'VARCHAR(16)',
        '-vc24-': 'VARCHAR(24)',
        '-vc32-': 'VARCHAR(32)',
        '-vc64-': 'VARCHAR(64)',
        '-vc100-': 'VARCHAR(100)',
        '-vc128-': 'VARCHAR(128)',
        '-vc255-': 'VARCHAR(255)',
        '-nv-': 'NVARCHAR',
        '-nvc8-': 'NVARCHAR(8)',
        '-nvc16-': 'NVARCHAR(16)',
        '-nvc24-': 'NVARCHAR(24)',
        '-nvc32-': 'NVARCHAR(32)',
        '-nvc64-': 'NVARCHAR(64)',
        '-nvc100-': 'NVARCHAR(100)',
        '-nvc128-': 'NVARCHAR(128)',
        '-nvc255-': 'NVARCHAR(255)',
        '-tx-': 'TEXT',
        '-ai-': 'AUTO_INCREMENT',
        '-nn-': 'NOT NULL',
        '-un-': 'UNIQUE',
        '-nnun-': 'NOT NULL UNIQUE',
        '-df-': 'DEFAULT',
        '-df0-': 'DEFAULT 0',
        '-df1-': 'DEFAULT 1',
        '-dfes-': "DEFAULT ''",
        '-dfcts-': 'DEFAULT CURRENT_TIMESTAMP',
        '-nndf-': 'NOT NULL DEFAULT',
        '-nndf0-': 'NOT NULL DEFAULT 0',
        '-nndf1-': 'NOT NULL DEFAULT 1',
        '-nndfes-': "NOT NULL DEFAULT ''",
        '-cn-': 'CONSTRAINT',
        '-pk-': 'PRIMARY KEY',
        '-fk-': 'FOREIGN KEY',
        '-rf-': 'REFERENCES',
        '-ours-': 'ON UPDATE RESTRICT',
        '-odrs-': 'ON DELETE RESTRICT',
        '-oucc-': 'ON UPDATE CASCADE',
        '-odcc-': 'ON DELETE CASCADE',
        '-ousd-': 'ON UPDATE SET DEFAULT',
        '-odsd-': 'ON DELETE SET DEFAULT',
        '-ousn-': 'ON UPDATE SET NULL',
        '-odsn-': 'ON DELETE SET NULL',
        '-ouna-': 'ON UPDATE NO ACTION',
        '-odna-': 'ON DELETE NO ACTION',
        '-ck-': 'CHECK',
        '-idx-': 'INDEX',
        '-ng-': 'ENGINE=',
        '-nginno-': 'ENGINE = INNODB',
        '-cm-': 'COMMENT =',
        '-sel-': 'SELECT',
        '-sel a-': 'SELECT *',
        '-fr-': 'FROM',
        '-sel afr-': 'SELECT * FROM',
        '-wh-': 'WHERE',
        '-gb-': 'GROUP BY',
        '-odb-': 'ORDER BY',
        '-ins-': 'INSERT INTO',
        '-val-': 'VALUES',
        '-ud-': 'UPDATE',
    }

    static parse(sqlsContent) {
        for (let key in this.aliases) {
            sqlsContent = sqlsContent.replaceAll(key, this.aliases[key])
        }
        return sqlsContent
    }
}
